services:
  ecommerce-backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=index
      - FLASK_ENV=production
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: vapestore
      MYSQL_USER: lia
      MYSQL_PASSWORD: lia
      MYSQL_ROOT_PASSWORD: lia123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
