swagger: '2.0'
info:
  title: Product Management API
  description: API for managing products
  version: 1.0.0
host: localhost:5000
basePath: /
schemes:
  - http
paths:
  /products:
    post:
      summary: Add a new product
      parameters:
        - name: product
          in: body
          description: Product to add
          required: true
          schema:
            type: object
            properties:
              user_id:
                type: integer
              category_id:
                type: integer
              title:
                type: string
              description:
                type: string
              stock:
                type: integer
              price:
                type: number
                format: float
              promotion:
                type: string
            required:
              - user_id
              - category_id
              - title
              - description
              - stock
              - price
              - promotion
      responses:
        201:
          description: Product added successfully
        400:
          description: Failed to add product
    get:
      summary: Get all products
      parameters:
        - name: category_id
          in: query
          type: integer
        - name: user_id
          in: query
          type: integer
        - name: page
          in: query
          type: integer
          default: 1
        - name: per_page
          in: query
          type: integer
          default: 10
      responses:
        200:
          description: A list of products
          schema:
            type: object
            properties:
              total:
                type: integer
              page:
                type: integer
              per_page:
                type: integer
              products:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    user_id:
                      type: integer
                    category_id:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    stock:
                      type: integer
                    price:
                      type: number
                      format: float
                    promotion:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
  /products/{id}:
    get:
      summary: Get a product by ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Product found
          schema:
            type: object
            properties:
              id:
                type: integer
              user_id:
                type: integer
              category_id:
                type: integer
              title:
                type: string
              description:
                type: string
              stock:
                type: integer
              price:
                type: number
                format: float
              promotion:
                type: string
              created_at:
                type: string
                format: date-time
              updated_at:
                type: string
                format: date-time
        404:
          description: Product not found
    put:
      summary: Update a product by ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - name: product
          in: body
          description: Product details to update
          required: true
          schema:
            type: object
            properties:
              category_id:
                type: integer
              title:
                type: string
              description:
                type: string
              stock:
                type: integer
              price:
                type: number
                format: float
              promotion:
                type: string
      responses:
        200:
          description: Product updated successfully
        400:
          description: Failed to update product
        404:
          description: Product not found
    delete:
      summary: Delete a product by ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Product deleted successfully
        404:
          description: Product not found
